const services = [
    { id: 102, name: 'Tire Replase', price: 1500, time: '2 hour', serviceImg: 'https://ibb.co/jy1tSfD', description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Autem, molestiae. Perspiciatis porro labore, asperiores enim delectus dicta. Ab voluptatum commodi ex, numquam dolores, quasi deleniti, necessitatibus exercitationem quos alias dolorum?' },
    { id: 103, name: 'car wash', price: 2000, time: '3 hour', serviceImg: 'https://ibb.co/LNJx5gG', description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Autem, molestiae. Perspiciatis porro labore, asperiores enim delectus dicta. Ab voluptatum commodi ex, numquam dolores, quasi deleniti, necessitatibus exercitationem quos alias dolorum?' },
    { id: 104, name: 'Engin Repair', price: '4500', time: '1 day', serviceImg: 'https://ibb.co/TcgQdN9', description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Autem, molestiae. Perspiciatis porro labore, asperiores enim delectus dicta. Ab voluptatum commodi ex, numquam dolores, quasi deleniti, necessitatibus exercitationem quos alias dolorum?' },
    { id: 105, name: 'Oil Change ', price: 500, time: '30 minute', serviceImg: 'https://ibb.co/SK8tTwL', description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Autem, molestiae. Perspiciatis porro labore, asperiores enim delectus dicta. Ab voluptatum commodi ex, numquam dolores, quasi deleniti, necessitatibus exercitationem quos alias dolorum?' },
    { id: 106, name: 'Test Driving', price: 1000, time: '1 hour', serviceImg: 'https://ibb.co/RzZXDrt', description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Autem, molestiae. Perspiciatis porro labore, asperiores enim delectus dicta. Ab voluptatum commodi ex, numquam dolores, quasi deleniti, necessitatibus exercitationem quos alias dolorum?' },
    { id: 107, name: 'Color Car Body', price: '5000', time: '3 days', serviceImg: 'https://ibb.co/580mgfd', description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Autem, molestiae. Perspiciatis porro labore, asperiores enim delectus dicta. Ab voluptatum commodi ex, numquam dolores, quasi deleniti, necessitatibus exercitationem quos alias dolorum?' }

]

